---
resources:
- name: resource-source
  type: git
  source:
    uri: https://github.com/change/me.git
    branch: master

- name: source-docker-image
  type: docker-image
  source:
    repository: {{docker-hub-image-name}}
    email: {{docker-hub-email}}
    username: {{docker-hub-username}}
    password: {{docker-hub-api-key}}

jobs:
- name: job-build-docker
  public: true
  serial: true
  plan:
    - get: resource-source
      trigger: true
    - task: job-build
      file: resource-source/ci/tasks/package.yml
    - put: source-docker-image
      params:
        build: resource-jar